import {
  FaHtml5,
  FaCss3Alt,
  FaJsSquare,
  FaNodeJs,
  FaReact,
  FaVuejs,
  FaDatabase,
  FaPython,
  FaGithub,
} from "react-icons/fa";
import {
  SiTailwindcss,
  SiExpress,
  SiNextdotjs,
  SiVite,
  SiMysql,
  SiMongodb,
  SiSwagger,
  SiN8N,
  SiPhp,
  SiBootstrap,
  SiTypescript,
  SiGreensock,
  SiFirebase,
  SiSupabase,
  SiVercel,
  SiGit,
  SiPrisma,
  SiEslint,
  SiPrettier,
  SiJest,
  SiTestinglibrary,
  SiPlaywright,
  SiReactquery,
  SiZod,
  SiFramer,
  SiShadcnui,
  SiPostgresql,
} from "react-icons/si";
import {
  Sparkles,
  Plug,
  Bot,
  Cpu,
  BrainCircuit,
  Atom,
  Wand2,
  FileCode2,
  Palette,
  Orbit,
  Cuboid,
  Workflow,
  Network,
  KeyRound,
  Lock,
  ArrowLeftRight,
  Server,
  MonitorSmartphone,
  Blocks,
  Webhook,
  ListChecks,
  Boxes,
  Link2,
  Package,
  FileJson,
} from "lucide-react";

export const iconMap = {
  html5: FaHtml5,
  css3: FaCss3Alt,
  javascript: FaJsSquare,
  nodejs: FaNodeJs,
  react: FaReact,
  vue: FaVuejs,
  database: FaDatabase,
  tailwind: SiTailwindcss,
  express: SiExpress,
  nextjs: SiNextdotjs,
  vite: SiVite,
  mysql: SiMysql,
  mongodb: SiMongodb,
  sparkles: Sparkles,
  plug: Plug,
  bot: Bot,
  cpu: Cpu,
  brain: BrainCircuit,
  atom: Atom,
  swagger: SiSwagger,
  n8n: SiN8N,
  wand: Wand2,
  php: SiPhp,
  bootstrap: SiBootstrap,
  vanilla: FileCode2,
  uiux: Palette,
  typescript: SiTypescript,
  gsap: SiGreensock,
  orbit: Orbit,
  cuboid: Cuboid,
  postgresql: SiPostgresql,
  firebase: SiFirebase,
  firestore: SiFirebase,
  supabase: SiSupabase,
  python: FaPython,

  // Tooling & DevOps
  vercel: SiVercel,
  git: SiGit,
  github: FaGithub,
  cicd: Workflow,
  eslint: SiEslint,
  prettier: SiPrettier,
  husky: Webhook,
  lintstaged: ListChecks,

  // Architecture & backend
  prisma: SiPrisma,
  apidesign: Network,
  authentication: KeyRound,
  authorization: Lock,
  middleware: ArrowLeftRight,
  serveractions: Server,

  // Frontend engineering
  responsive: MonitorSmartphone,
  componentarch: Blocks,
  shadcn: SiShadcnui,
  json: FileJson,

  // Testing & quality
  jest: SiJest,
  rtl: SiTestinglibrary,
  playwright: SiPlaywright,

  // State & data
  tanstackquery: SiReactquery,
  reactcontext: Boxes,
  reacthooks: Link2,
  zustand: Package,
  zod: SiZod,
  framer: SiFramer,
};

export function SkillIcon({ name, className }) {
  const Icon = iconMap[name] || Sparkles;
  return <Icon className={className} aria-hidden="true" />;
}